#ifndef DOSER_CUSTOM_CONFIG	

	#define PUMP_ONE_BTN_PIN 23
	#define PUMP_ONE_RELAY_PIN 19
	#define PUMP_TWO_BTN_PIN 5
	#define PUMP_TWO_RELAY_PIN 18
	#define PUMP_THREE_BTN_PIN 15 
	#define PUMP_THREE_RELAY_PIN 16
	#define PUMP_FOUR_BTN_PIN 4
	#define PUMP_FOUR_RELAY_PIN 32
	#define PUMP_FIVE_BTN_PIN  25
	#define PUMP_FIVE_RELAY_PIN 33
	#define PUMP_SIX_BTN_PIN 27
	#define PUMP_SIX_RELAY_PIN 26
	#define WIFI_LED_PIN 13
	#define MQTT_LED_PIN 14
	
#endif